name: Build and Publish Rust Containers

on:
  push:
    branches:
      - main

  workflow_dispatch:

# Set environment variables for the container registry and image name
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Set as current repo. Can change to alternate if these shifted to another location.

jobs:
  build-and-publish:
    name: Build and Publish Docker Container(s)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/login-action
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ${{ env.GITHUB_REPOSITORY_OWNER }}/${{ github.repository }}
            ghcr.io/${{ github.repository }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            API_KEY=Test123
            GOOGLE_CLOUD_KEY=${{ secrets.CLOUDKEY }}
            GOOGLE_PROJECT_ID=${{ secrets.PROJECTID }}
            A11Y_URL=${{ secrets.A11YURL }}
            A11Y_JWT=
            GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLEAPPCREDS }}

  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
  push_to_registries:
    name: Push Docker image to Dockerhub
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            my-docker-hub-namespace/my-docker-hub-repository
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#  deploy:
#   name: Deploy to Namespace
#  needs: build-and-publish
# runs-on: self-hosted
#steps:
#      - uses: actions/checkout@v3
#      - uses: azure/setup-kubectl@v3
#      - name: Deploy
#        run: kubectl apply --namespace=public-sector-a11y_connect -f k8s
